services:
  - type: background-worker
    name: wildwest-dice-bot
    env: node
    runtime: node
    buildCommand: npm install && npm install sqlite3 --build-from-source
    startCommand: cd /opt/render/project && node src/bot.js